Repository yasslab/railsguides.jp, pull requests merged in 2019-08, with the labels that each got.

#848 WIP: New active record multiple databases.md
  guides/source/ja/active_record_multiple_database.md
Labels: 新規翻訳

#869 訳文修正（Railsエンジンガイド）
  guides/source/ja/engines.md
Labels: 改善

#870 アップグレードガイドと6.0リリースノートのキャッチアップ翻訳
  guides/source/ja/6_0_release_notes.md
  guides/source/ja/upgrading_ruby_on_rails.md
Labels: 改善

#871 6.0キャッチアップ翻訳（続き）
  guides/source/ja/active_storage_overview.md
  guides/source/ja/active_support_core_extensions.md
  guides/source/ja/association_basics.md
  guides/source/ja/autoloading_and_reloading_constants.md
  guides/source/ja/caching_with_rails.md
  guides/source/ja/contributing_to_ruby_on_rails.md
  guides/source/ja/getting_started.md
  guides/source/ja/i18n.md
  guides/source/ja/maintenance_policy.md
  guides/source/ja/routing.md
  guides/source/ja/security.md
  guides/source/ja/testing.md
  guides/source/ja/working_with_javascript_in_rails.md
Labels: 更新翻訳

#874 testing.mdの英語残りを修正
  guides/source/ja/testing.md
Labels: 更新翻訳

#880 バナー画像に「15日間無料でお試し」の文言を追加
  guides/assets/images/bnr-pro-plan.jpg
  guides/assets/images/bnr_pro.jpg
  guides/assets/images/bnr_team.jpg
Labels: 改善
